name: Release/Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release 🖋
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
